### ISSUE TITLE
Generate RSA key pair from the available keys

### ISSUE THREAD

**Issue by ptmjanish** [henrinormak/Heimdall#17]
I usually call the regenerate function (which is needed) when my app opens. Is it possible to generate the key pair from the key pair available in the form of NSData?

**Comment by henrinormak** [comment]
I don't understand why calling regenerate is needed, could you elaborate? Currently Heimdall does not allow creating an instance with a private-public key, but you can create an instance with public key data, as well as an instance that creates both components for you. This is by design, as sharing a private key securely is not simple and thus Heimdall aims to not permit potentially harmful operations. If you feel otherwise, please elaborate and potentially file a pull request with code that allows exporting/initialising with both a public and private key.

**Comment by ptmjanish** [comment]
I know Heimdall usually stores the previously generated key pairs. But, In case if the app is re-installed (or entire data of the app is cleared), there will be a new pair of keys generated and that won't synchronise with the app network. So, here I get the keys from the server side in a secure network path (ensured) and I can convert it to NSData or Base64encoded string. Can I create the key from such a data. 

Also, the public key for the receiver is also received in such a way. How can I encrypt using that key

**Comment by henrinormak** [comment]
My question is simple, why does the server ever need to have a copy of the private key? In public key encryption, the other party ever only needs to see your public key, if for some reason you need to regenerate (be it the reasons you mentioned or something else), then you only need to update the public key on the server.

Also, as Heimdall stores key data in the system Keychain, reinstalling the app does not erase the data, only system restore/reinstall erases Keychain data (unless you specifically delete the entry yourself, or do so by calling regenerate every time).

If you are adamant that both the private as well as public key has to come from an outside source, then I suspect Heimdall is not a good fit for you, the intent of Heimdall was to abstract away from keysharing and offer a simple way to encrypt data for local storage or encrypt simple messages to be sent to another Heimdall instance, it was never meant to be a counterpart to a potentially complex system of different encryptors and decryptors (i.e it is not a complete wrapper around the capabilities of CommonCrypto).

In any case, you can create a Heimdall instance with public key data in X.509 format using the initialiser listed [here](https://github.com/henrinormak/Heimdall/blob/master/Heimdall/Heimdall.swift#L56) or alternatively if you have the key components as data (exponent and modulus), you can use the initialiser [here](https://github.com/henrinormak/Heimdall/blob/master/Heimdall/Heimdall.swift#L84). Both of these yield an instance that is able to encrypt, but not decrypt data (as decryption is handled by the private key).

**Comment by ptmjanish** [comment]
That was  a good answer. I was thinking that I'll lose the keys once the app is uninstalled. That's why I was thinking so stupid. Thanks for the answer.
