### ISSUE TITLE
CSR Generation capability?

### ISSUE THREAD

**Issue by dodgymike** [henrinormak/Heimdall#20]
Would it be possible to add CSR (Certificate Signing Request) generation capability to Heimdall?

**Comment by henrinormak** [comment]
Not sure this is something that should be part of Heimdall, could you explain your use case for this in the context of Heimdall?

**Comment by dodgymike** [comment]
My iOS app needs to interact with an API that requires a certificate signed by its CA, and it only accepts CSRs, not SCEP :(

Since Heimdall is a nice wrapper around the iOS native security calls, I thought it would be a useful/natural part of it?

**Comment by henrinormak** [comment]
I see, I don't currently have the time to look into CSR generation on iOS (I know for a fact that there is no, one, API for it), so I will have to postpone this. If you have time to create or port an existing CSR generation function over, I would gladly look at the pull request.

**Comment by dodgymike** [comment]
Ok, thanks. I am currently busy writing a class to do that. Unfortunately it isn't pretty, both because I'm new to Swift and because of the required steps to generate ASN.1-based structures in Swift!

When I'm done I'll add it to Heimdall, and you can look over it :)

**Comment by henrinormak** [comment]
Thank you! :+1:
