### ISSUE TITLE
Add TVOS target

### ISSUE THREAD

**Issue by kyle-dorman** [henrinormak/Heimdall#26]

**Comment by henrinormak** [comment]
Could you elaborate, not that familiar with tvOS. Is this mostly about adding a modulemap for CommonCrypto?

**Comment by kyle-dorman** [comment]
Created a pull request. Yea mostly just adding a modulemap for crypto and then a new framework specific to tvos.

**Comment by henrinormak** [comment]
I've migrated the changes under #29 as that one is a bit more complete than yours was, hope you don't mind! :+1:
