### ISSUE TITLE
Cocoapod support?

### ISSUE THREAD

**Issue by jlaws** [henrinormak/Heimdall#3]
https://cocoapods.org/

**Comment by henrinormak** [comment]
As I am not as familiar with Swift and CocoaPods, could you create a pull request with this? Alternatively, I can look into this, but that might take some time.

**Comment by jlaws** [comment]
As the repo owner you will need to register the repo on cocoapods.  It is worth taking the time to learn, and should only take a couple hours.

**Comment by henrinormak** [comment]
Alright, I'll look into it, my main concern is with CommonCrypto usage, the current system I have in place might not work nicely with CocoaPods.

**Comment by henrinormak** [comment]
After spending a while, CocoaPods are now supported. For future reference and anyone looking for a way to use CommonCrypto in a CocoaPod, look at the Podspec, mainly the way it uses static modulemaps and some fancy footwork to make sure the CommonCrypto import works.

**Comment by jlaws** [comment]
awesome! thanks @henrinormak
