### ISSUE TITLE
Error -9809 when decrtyp data from another device

### ISSUE THREAD

**Issue by thangk48cc** [henrinormak/Heimdall#38]
i created a Heimall and got X509 key. 
i share it for another device. another device get it and create another Heimall with X509 key. next from another device encrypt 1 message and send it to first device. on this device decrypt and get err

errSSLCrypto   -9809    An underlying cryptographic error was encountered.

why? can you help me?

**Comment by henrinormak** [comment]
Any chance of getting a minimal implementation that reproduces this? A public key might also help (i.e the data that you get from one device to use with the other). Otherwise it is really difficult to diagnose.

**Comment by thangk48cc** [comment]
thanks you 

i have resolved it. error when create key. encrypt and decrypt.

closed issue
