### ISSUE TITLE
intermittent failure decrypting... (???)

### ISSUE THREAD

**Issue by hools** [henrinormak/Heimdall#41]
Not really sure how to perfectly describe my problem =(. I am using the latest version available via cocoapods and latest Swift. I am encrypting both text, e.g.  `String = "foo"` and also images after base64 encoding them e.g. 
`let _imageData = UIImageJPEGRepresentation(image, compressionFactor)`
`let _encodedString = _imageData!.base64EncodedStringWithOptions(NSDataBase64EncodingOptions())`

I use a 2048 size key e.g. `Heimdall(tagPrefix: key, keySize: 2048)` and when I encrypt and decrypt I use `urlEncode: false` since the data is stored in a back end that doesn't need url encoding.
I decrypt simply by: 
`if let clearText = my_Heimdall_instance.decrypt(encrypted_text, urlEncoded: false) as String? { ...}`
So far so good. It's a chat application. it works great! except every now and again, seemingly without any pattern, decryption fails and returns nil. It's almost random and happens once every 20 to 100 messages. Sometimes with plain text messages, sometimes with images. I suspect some weird boundary condition (**padding**?) but I can't figure it out! The encrypted content looks normal and the length seems reasonable

Any ideas?? [_there may be a small reward for the first person to solve it!_]

Thanks! =)

ps: FWIW, here is an example of an encrypted message that failed to decrypt. It's a few simple words as a String:
`jNCNYe8NPgqs3jspfGGiOwa/AkRb5PBWSp0FFvVdvMrMU50/0ti8j4SpYF+/OlcaeorpItuqEymU/mNB9PhHaV7IhxTPk8STcEs0o8KynHq1l7bHQ6gkHCMwhTxgNBeB+Mvctv5Pxxxg3+ESUmCKMH4G9+skC63Mamcm5BIRqokoL3lxnHaz77j0N09jP0rAkBY0jwN0myGrp2JV1cqLzzkWkTOYFkzgReMqRgrf3c2c9/vrRCPLk9umGGFq/YfCZXfpFja6C3OwPulgoKFxu/qX2hYAUZdJrZ0ao1/bL+xkSLvnOw/dXaR3FAxggFhzvbb/7+AVbnW3clvOF2gzLN05igEB6vxQuX0rQ9QLRop5hgR157LepY+EJtwBnSocPeYJ94MqoV0IeuFuevhuOXycAcyGwTHosdQX4pl7JzRs1oZR7wLJJgV4UDYF/uVXhp3X744+doefZsOvMnjddA==`

**Comment by henrinormak** [comment]
I can try and create a few longer running test cases which try to emulate encrypting and decrypting more than a few messages. These will make the test suite run a lot longer, but should also help give a performance metric for both operations.

Can't give you a deadline on this, but will do my best to help you out soon.

**Comment by hools** [comment]
also keep in mind that the failure to decrypt happens right after a bunch of successful decrypts...and immediately after a bad message, usually the next one is good. even the same exact content (copy paste) works the second time. I also checked the back-end data with the data downloaded and it's exact. So I don't suspect any data loss during upload or download. And keys are good since other messages work before and after the bad one.... (???)

**Comment by hools** [comment]
I heard that sometimes iOS keychain reads fail!? and return incorrect data!?. The suggestion was to store a hash of the key separately and compare the key retrieved with the hash. If it's good, keep it in memory for the duration of the app session, instead of constantly retrieving the key. 

what do you think of this?

**Comment by henrinormak** [comment]
I don't really like the idea of keeping the key around for longer than the single operation, but verifying the key sounds like a potentially good idea. Granted, this would be quite an overhaul, as it requires generating the hash (even for existing keys) and then using said hash before using the keys.

**Comment by henrinormak** [comment]
I've added performance test that does a 100 passes that encrypt and then decrypt the data, the results are then verified. If you can, please run this test and tweak the test data to best match the scenario in which you are seeing the issue occur.

https://github.com/henrinormak/Heimdall/blob/master/HeimdallTests/HeimdallTests.swift#L200-L223

**Comment by hools** [comment]
Thanks Henri!

Unfortunately I have run the test and it passes. I haven't been able to reproduce the decryption failure anywhere outside my app. I'll keep trying to figure it out but otherwise I may have to abandon your fine library and go off on my own =(  ... [don't want to do that!]

let's leave the issue open for the moment, maybe I'll figure it out.

-- hools

**Comment by hools** [comment]
Well, I tried and could not adequately reproduce the issue. We should close it. Thanks!
