### ISSUE TITLE
Compilation error - redefinition of module CommonCrypto

### ISSUE THREAD

**Issue by omerlh** [henrinormak/Heimdall#42]
Hey
I've just installed Heimdall in my project using cocoapods. When I've tried to compile it using XCode 7.3, I've got the following error: 

```
path-to-project/Pods/Heimdall/CommonCrypto/appletvsimulator/module.modulemap:1:8: Redefinition of module 'CommonCrypto'
path-to-project/Pods/Heimdall/CommonCrypto/appletvos/module.modulemap:1:8: Previously defined here
```

it happen also for the iphone simulator map. I think this is because I have another pod [(Branch](https://github.com/BranchMetrics/ios-branch-deep-linking) that depend on CommonCrypto, but I am not sure what to do in order to solve it.

Hope you could help with this mysterious error,
Omer

**Comment by sadaf-behbahani** [comment]
I have the same issue with Xcode 10. Any idea ?

**Comment by henrinormak** [comment]
Discussed/handled in #72
