### ISSUE TITLE
Generate RSA using Modulus and Exponent

### ISSUE THREAD

**Issue by kosicki123** [henrinormak/Heimdall#5]
Hi, I need to create an RSA Key providing a modulus and an exponent. Not sure if that is currently possible using Heimdall. 
I'll be glad with help of any kind! Thanks

**Comment by henrinormak** [comment]
It is not currently directly possible, however, if you were to take care of converting the exponent and modulus to the X.690 format (Basic Encoding Rules - BER) and then feed that data into Heimdall it should work. 

You could look into using this [SCZ-BasicEncodingRules-iOS](https://github.com/StCredZero/SCZ-BasicEncodingRules-iOS) to do the conversion for now. I will look into adding a direct method, which would allow initialising a Heimdall instance with integer/base64 modulus and exponent, it seems relatively similar to what the X.509 export is already doing.

Once you have an instance, you could then use it for encryption/verification, as well as for exporting the public key as a X.509 data blob.

**Comment by kosicki123** [comment]
I'll take a look on SCZ, but will keep follow your repository for future direct implementation of Mod and Exp. Thanks a lot for your time!

**Comment by henrinormak** [comment]
As of 5cb0da5bf666302c376fc402539fadb4e0aa2b55 Heimdall should support initialising with modulus/exponent. Both are also exportable from an existing instance.

**Comment by kosicki123** [comment]
Hey, thanks for the update. I've been trying to use Heimdall since then.
Probably doing something wrong here, but I can't make it work as it's supposed to.
Somehow the result is invalid, if you could take a look at this gist, I'll be glad.
Probably I made some mistake on the implementation.
https://gist.github.com/kosicki123/18f4e4d74c84e7c034cb

**Comment by henrinormak** [comment]
I replied to the gist, let's discuss it there. From the tests I conducted, modulus and exponent should both be NSData that is based on a big integer (usually you store that integer as Base64, seeing as it is far too large to store as a plain integer type).
