### ISSUE TITLE
Not able to pull 1.1.0

### ISSUE THREAD

**Issue by emreakman1991** [henrinormak/Heimdall#52]
I am trying to use the latest release 1.1.0 in my project, but i am unable to. But this is what i get when trying to install it in my project using cocoapods.

<img width="480" alt="screen shot 2016-10-21 at 16 27 35" src="https://cloud.githubusercontent.com/assets/3736780/19601874/5140b3a8-97ab-11e6-9f65-88bc38c4093b.png">

**Comment by schoenr** [comment]
same for me, I just use 
`pod 'Heimdall', :git => 'https://github.com/henrinormak/Heimdall.git'`
to get the 1.1.0 version

**Comment by henrinormak** [comment]
Seems like the latest version was not pushed to cocoapods trunk, will fix.

**Comment by henrinormak** [comment]
Fixed, latest version 1.1.2 can be correctly pulled from CocoaPods.
