### ISSUE TITLE
Compatibility with Crypto++

### ISSUE THREAD

**Issue by nitrodamsel** [henrinormak/Heimdall#65]
Hi I just want to know if its RSA encryption / decryption is compatible with Crypto++? We're trying cross platform but its crashing when I'm trying to use his public RSA (from Android-NDK).

**Comment by henrinormak** [comment]
I have not heard of that library, and as such I am inclined to say that it is likely not compatible. You can refer to the [README](https://github.com/henrinormak/Heimdall#note-on-encryptiondecryption) for insight into how the encryption works (which is not vanilla RSA). Regards to the crash, more information would be necessary to understand the problem.
