### ISSUE TITLE
Cocoapods: Absolute path in modulemap causes build issues on some machines

### ISSUE THREAD

**Issue by pvegh** [henrinormak/Heimdall#66]
In all modulemap files e.g.:
https://github.com/henrinormak/Heimdall/blob/master/CommonCrypto/iphonesimulator.modulemap

I am not too deeply knowledgable how Cocoapods exactly works but I would hope there is a better way to do this. Something like this would be my first guess:
https://github.com/onmyway133/Arcane/blob/master/Sources/CCommonCrypto/module.modulemap

Basically my problem is that while I can adjust the path locally for my system, the Pods are not committed to Git so Jenkins will never be able to build (multiple Xcode installations with different paths).

Thanks for any suggestions.

**Comment by henrinormak** [comment]
As I am not that familiar with CocoaPods (I use Carthage these days), would you mind making a PR that would fix this problem? I would love to get it working (as I have tried already), but as it seems, my attempt has not been a success.

**Comment by pvegh** [comment]
Sorry but I don't think I can help with that anytime soon.
