### ISSUE TITLE
Import private key from keystore

### ISSUE THREAD

**Issue by ced236** [henrinormak/Heimdall#68]
Hello, 

Is it possible to import a private key from a keystore ( a  .p12 file in my case) and use it to do a RSA encryption ?

**Comment by henrinormak** [comment]
No, Heimdall doesn't really do RSA encryption. As RSA has a fixed block size (depends on key size), it is not really suitable for variable length text encryption. Instead you can read how Heimdall encrypts things in the [README](https://github.com/henrinormak/Heimdall#note-on-encryptiondecryption)
