### ISSUE TITLE
Encrypted string is nil with public key data encryption

### ISSUE THREAD

**Issue by testower** [henrinormak/Heimdall#7]
I invariably get nil when I try to encrypt a String using a public key data object that I have generated. I was hoping you would be able to give me some pointers to how to debug this.

```
// On device A
let heimdall = Heimdall(tagPrefix: "com.example.app", keySize: 2048)
let publicKeyData = heimdall?.X509PublicKey()
var keyString = publicKeyData?.base64EncodedStringWithOptions(.allZeros)

// then later on Device B
let keyData = NSData(base64EncodedString: keyString, options: NSDataBase64DecodingOptions.allZeros)
let heimdall = Heimdall(publicTag: "com.example.app", publicKeyData: keyData)
let encrypted = heimdall?.encrypt(message, urlEncode: false)

println(encrypted) // nil - :-(
```

I realize I may be doing something wrong with the tagPrefix/publicTag parameters, but not sure how to use them as the docs are a little unclear.

**Comment by henrinormak** [comment]
I'll start from explaining tagPrefix - it'll create two different tags, one for public key and the other for private key by appending ".private" to the prefix. Alternatively you can provide both tags yourself, which is good for cases where you might already have keys that were generated with a different set of tags.

Your code seems OK, I ran a quick test and it seemed to be fine (i.e encrypted was non-nil), which leads me to suspect either of two things is happening:
- On device B, Heimdall instance is not created (returns nil, which then returns nil on the encryption line), which would hint that there is something wrong with the key data (or a bug in Heimdall)
- There is something unique about the message being encrypted, but as you say it always occurs, then this is likely not the case

Could you confirm if on device B the instance is created? Also, could you confirm that keyString is indeed non-nil.

**Comment by testower** [comment]
Thanks for getting back to me so soon! 

I've isolated the problem in a fresh project, in a single class, i.e. both the key generation and the encryption executed on the same device (iOS simulator).

 The project is a simple single-view application, with Heimdall installed via cocoapods with the use_frameworks! option.

The code looks the like this, with print-lines embedded with results (key data truncated):

```
import Foundation
import Heimdall

class TestHeimdall {

    var publicKey: String?

    func generatePublicKey() {
        let heimdall = Heimdall(tagPrefix: "com.example.HeimdallTest", keySize: 2048)
        let publicKeyData = heimdall?.X509PublicKey()
        self.publicKey = publicKeyData?.base64EncodedStringWithOptions(.allZeros)
        println(self.publicKey) // Optional("MIIBIjA ...")
    }

    func encryptWithPublicKey() {
        println(self.publicKey) // Optional("MIIBIjA ...")
        let publicKeyData = NSData(base64EncodedString: self.publicKey!, options: .allZeros)
        println(publicKeyData) // Optional(<30820122 300d0609 ... >)
        let heimdall = Heimdall(publicTag: "com.example.HeimdallTest", publicKeyData: publicKeyData)
        println(heimdall) // Optional(Heimdall.Heimdall)
        let encrypted = heimdall?.encrypt("encrypt this message", urlEncode: false)
        println(encrypted) // nil
    }
}
```

The code is executed in ViewController's viewDidLoad:

```
let test = TestHeimdall()
test.generatePublicKey()
test.encryptWithPublicKey()
```

Thanks for any advise you can give in debugging further.

**Comment by henrinormak** [comment]
I got this to reproduce, I will investigate as soon as possible. The main issue seems to be with fetching the key after it has been created, unclear what is going on. Will update you as I make progress.

**Comment by henrinormak** [comment]
The issue was related to X.509 stripping (which is required as Keychain doesn't like the header info). This would've been spotted earlier with appropriate unit tests, thus raising the priority for having those.
