### ISSUE TITLE
XCode 10: redefinition of module 'CommonCrypto'

### ISSUE THREAD

**Issue by nabbestemmia** [henrinormak/Heimdall#72]
I'm trying to run my project with XCode 10 beta, but I get an error saying: redefinition of module 'CommonCrypto'.

Showing All Messages
Failed to emit precompiled header '.../Library/Developer/Xcode/DerivedData/dukzbmbkgxmidoaaqsvrwtawkugp/Build/Intermediates.noindex/PrecompiledHeaders/Bridging-Header-swift_2EL3O7W05IR7C-clang_1MOIT4BKL3MYZ.pch' for bridging header '.../Bridging-Header.h'

**Comment by sadaf-behbahani** [comment]
I have the same issue. Do you have any idea ?

**Comment by YJSai** [comment]
go to CommonCrypto directory, check any .modulmap files then you can find how they declare module name like below 

module CommonCrypto [system] {
}

replace 'CommonCrypto' to any name you prefer
and also change the imported module name to new name

**Comment by jaelee1993** [comment]
Did ^^ fix work guys? Having the same issue here

**Comment by zlata** [comment]
Any update? Having the same issue here

**Comment by zlata** [comment]
Deleting folder Pods/Heimdall/CommonCrypto fixing this issue. Here's fix for packaging https://github.com/jonblatho/JSONWebToken.swift/commit/44f4b7a4ed7c1d2a165e106f2eb236ad199a54be

**Comment by einarnot** [comment]
Please include a fix for this in the repo

**Comment by henrinormak** [comment]
As I have been quite distant from iOS development for a while, if you could open a PR I would gladly merge a fix (assuming it will work as the sole dependency declaring CommonCrypto as well as with others).

**Comment by henrinormak** [comment]
This should be fixed as of #73/#74 (thanks @einarnot for the PR), please confirm and I'll close the issue. Pushed 2.0.0 release/tag with the fix.

**Comment by einarnot** [comment]
It now works, but I introduced a bug causing device-builds to fail. Created a new PR with a fix. https://github.com/henrinormak/Heimdall/pull/76

**Comment by henrinormak** [comment]
Thanks, I will push this to cocoapods soon (don't have access to cocoapods atm), tagged the release already though - 2.0.1

**Comment by mobihunterz** [comment]
> Deleting folder Pods/Heimdall/CommonCrypto fixing this issue. Here's fix for packaging [jonblatho/JSONWebToken.swift@44f4b7a](https://github.com/jonblatho/JSONWebToken.swift/commit/44f4b7a4ed7c1d2a165e106f2eb236ad199a54be)

Worked for me as well. My issues was with Mattress pod. CommonCrypto is not related to particular framework I believe.
