### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by JakeTorres** [henrinormak/Heimdall#78]
Heimdall is work for base64 not RSA?

**Comment by henrinormak** [comment]
Not sure what you mean by this question, Heimdall uses a symmetric key to actually encrypt the text (as RSA has a length limit on how much data it can encrypt), then encrypts the symmetric key with the RSA key. This is also documented in the [README](https://github.com/henrinormak/Heimdall#note-on-encryptiondecryption)

**Comment by henrinormak** [comment]
Marking as closed, nothing I can really help with here.

**Comment by JakeTorres** [comment]
thanks, ok now

**Comment by JakeTorres** [comment]
thanks ,it is work now
